tool:
  sam2:
    checkpoint: weights/sam2/sam2.1_hiera_large.pt
  depthAnything2:
    checkpoint: weights/depthAnything2/depth_anything_v2_metric_indoor_large.pth
  vggt:
    checkpoint: weights/vggt/model.pt